package com.julianleonard.game.service;

public enum GameStatus {
	AWAITING_PLAYER_1_JOIN,
	AWAITING_PLAYER_2_JOIN,
	AWAITING_PLAYER_1_MOVE,
	AWAITING_PLAYER_2_MOVE,
	GAME_OVER_PLAYER_1_WINNER,
	GAME_OVER_PLAYER_2_WINNER,
	GAME_OVER_NO_WINNER,
	GAME_OVER_PLAYER_DISCONNECTED
}
